CREATE OR REPLACE TABLE `CE_Appsheet_Layer.Creators` (Creator_ID STRING,
Entity_Type STRING,
Creator_Name STRING,
Creator_Picture STRING,
Creator_Bio STRING,
Creator_Age INT64,
Creator_Gender STRING,
Location STRING,
Artist BOOL,
Influencer BOOL,
Instagram STRING,
Facebook STRING,
Threads STRING,
YouTube STRING,
TikTok STRING,
Twitch STRING,
Spotify STRING,
Updated_By STRING,
Entity_ID STRING,
Updated_At TIME);
--Influencer_ID, Artist_ID are Virtual Columns added to AppSheet directly
