CREATE OR REPLACE TABLE `CE_Appsheet_Layer.Music_Artists` (Artist_ID INT64,
Entity_Type STRING,
Artist_Type STRING,
Artist_Name STRING,
Artist_Picture STRING,
Artist_Bio STRING,
Artist_Genre STRING,
Num_Songs INT64,
Num_Albums INT64,
NUm_Awards INT64,
Updated_By STRING,
Updated_At Date);
