CREATE OR REPLACE TABLE `CE_Appsheet_Layer.Social_Profile` (Social_Profile_ID INT64,
Creator_ID INT64,
Creator_Name STRING,
Social_Media_Plstform STRING,
Num_Followers INT64,
Num_Following INT64,
Num_Posts INT64,
Num_Conversations INT64,
Num_Streams INT64,
Num_Views INT64,
Watch_Time INT64,
Num_Uploads INT64,
Num_Shortform_Uploads INT64,
Shortform_Views INT64,
SHortform_WatchTime INT64,
Updated_By STRING,
Updated_At Date);
