CREATE OR REPLACE TABLE `CE_Appsheet_Layer.Trends_Videos` (Trend_ID STRING,
Trend_Name STRING,
Trend_Start_Date DATE,
Social_Platform_ID STRING,
Social_Platform_Name STRING,
Video_ID STRING,
Video_Title STRING,
Video_Url STRING,
Influencer_ID STRING,
Influencer_Name STRING,
Song_ID STRING,
Song_Name STRING,
Artist_ID STRING,
Artist_Name STRING,
Updated_By STRING,
Video_Content STRING,
Updated_At TIME);
