CREATE OR REPLACE TABLE `CE_Appsheet_Layer.Trends_Videos` (Trend_ID INT64,
Trend_Name STRING,
Trend_Start_Date DATE,
Social_Platform_ID INT64,
Video_ID INT64,
Video_Url STRING,
Creator_ID INT64,
Creator_Name STRING,
Artist_ID INT64,
Artist_Name STRING,
Influencer_ID INT64,
Influencer_Name STRING,
Updated_By STRING,
Updated_At Date);
