CREATE OR REPLACE TABLE `tech-cali-b2c.CE_Reporting_Layer.Creator_Reporting`
AS SELECT  
Artist_ID,
Creator_Name AS `Artist Name`,
Final_Selection_Score AS `Artist Selection Score`,
Audience_Score AS `Audience Score`, 
Content_Performance_Score AS `Content Performance Score`, 
Engagement_Score AS `Engagement Score`,
" " AS `Social Score`,
Audience_Score_Label AS `Audience Score Bucket`, 
Content_Performance_Score_Label AS `Content Performance Score Bucket`, 
Engagement_Score_Label AS `Engagement Score Bucket`,
" " AS `Social Score Bucket`,
Final_Selection_Score_Label AS `Artist Selection Score Bucket`,
youTube_subscribers AS `YouTube Subscribers`,
Youtube_Genz_subscribers AS `YouTube Genz Subscribers`,
spotify_followers AS `Spotify Followers`,
twitter_followers AS `Twitter Followers`,
instagram_followers AS `Instagram Followers`,
Instagram_Genz_followers AS `Instagram Genz Followers`,
TikTok_Followers AS `TikTok Followers`,
TikTok_Genz_followers AS `TikTok Genz Followers`,
spotify_monthly_listeners AS `Spotify Listeners`,
twitter_retweets AS `Twitter Retweets`,
TikTok_total_creations_for_top_n_tracks AS `TikTok Creations`,
TikTok_total_views_for_top_n_tracks AS `TikTok Views`,
youtube_monthly_video_views AS `YT Views`,
facebook_likes AS `Likes`,
facebook_talks AS `Talks`,
Instagram_avg_engagements_per_post AS `Instagram Enagagements`,
TikTok_avg_engagements_per_post AS `TikTok Engagements`,
Youtube_avg_engagements_per_post AS `YouTube Engagements`
FROM `tech-cali-b2c.CE_ML_Layer.Creator_Selection_Profile`,
UNNEST(Z_Score) AS Z_Score_alias,
UNNEST(Audience) AS Audience_alias,
UNNEST(Content_Performance) AS Activity_alias,
UNNEST(Engagement) AS Engagement_alias;
