CREATE OR REPLACE TABLE `tech-cali-b2c.CE_Reporting_Layer.Creator_Reporting`
AS SELECT  
Artist_ID,
Creator_Name,
Final_Selection_Score,
Audience_Score, 
Content_Performance_Score, 
Engagement_Score,
" " AS Social_Score,
Audience_Score_Label As Audience_Score_Bucket, 
Content_Performance_Score_Label AS Content_Performance_Score_Bucket, 
Engagement_Score_Label AS Engagement_Score_Bucket,
" " AS Social_Score_Bucket,
Final_Selection_Score_Label AS Final_Selection_Score_Bucket,
SAFE_CAST(youTube_subscribers AS FLOAT64) AS YouTube_Subscribers,
SAFE_CAST(Youtube_Genz_subscribers AS FLOAT64) AS YouTube_Genz_Subscribers,
SAFE_CAST(Youtube_Genz_subscribers_percentage AS FLOAT64) AS Youtube_Genz_subscribers_percentage,
SAFE_CAST(spotify_followers AS FLOAT64) AS Spotify_Followers,
SAFE_CAST(twitter_followers AS FLOAT64) AS Twitter_Followers,
SAFE_CAST(instagram_followers AS FLOAT64) AS Instagram_Followers,
SAFE_CAST(Instagram_Genz_followers AS FLOAT64) AS Instagram_Genz_Followers,
SAFE_CAST(Instagram_Genz_followers_percentage AS FLOAT64) AS Instagram_Genz_followers_percentage,
SAFE_CAST(TikTok_Followers AS FLOAT64) AS TikTok_Followers,
SAFE_CAST(TikTok_Genz_followers AS FLOAT64) AS TikTok_Genz_Followers,
SAFE_CAST(TikTok_Genz_followers_percentage AS FLOAT64) AS TikTok_Genz_followers_percentage,
SAFE_CAST(spotify_monthly_listeners AS FLOAT64) AS Spotify_Listeners,
SAFE_CAST(twitter_retweets AS FLOAT64) AS Twitter_Retweets,
SAFE_CAST(TikTok_total_creations_for_top_n_tracks AS FLOAT64)AS TikTok_Creations,
SAFE_CAST(TikTok_total_views_for_top_n_tracks AS FLOAT64) AS TikTok_Views,
SAFE_CAST(youtube_monthly_video_views AS FLOAT64) AS YT_Views,
SAFE_CAST(facebook_likes AS FLOAT64) AS Facebook_Likes,
SAFE_CAST(facebook_talks AS FLOAT64) AS Facebook_Talks,
SAFE_CAST(Instagram_avg_engagements_per_post AS FLOAT64) AS Instagram_Enagagements,
SAFE_CAST(TikTok_avg_engagements_per_post AS FLOAT64) AS TikTok_Engagements,
SAFE_CAST(Youtube_avg_engagements_per_post AS FLOAT64) AS YouTube_Engagements
FROM `tech-cali-b2c.CE_ML_Layer.Creator_Selection_Profile`,
UNNEST(Z_Score) AS Z_Score_alias,
UNNEST(Audience) AS Audience_alias,
UNNEST(Content_Performance) AS Activity_alias,
UNNEST(Engagement) AS Engagement_alias;
